### ISSUE TITLE
Code organization: private subviews

### ISSUE THREAD

**Issue by ssayfulin69** [RedMadRobot/RMR-swift-style-guide#25]
Do you imply that private subviews list should be placed above public properties?
There are some developers building subviews in code rather than using interface builder.

I assume that IBOutlets are more or less public, being linked to Storyboard or Xib, and in their case it is right to place them at the first place. But private subviews do not stick up out of class and it is more correct to place public interface first. And then if person reading this code needs to find out implementation of the view, one can scroll down to subviews and layout.

**Comment by vani2** [comment]
Honestly speaking, we use the next order:

```swift
// MARK: - Public Properties

// MARK: - IBOutlet

// MARK: - Private Properties
```

Because of using `@IBOutlet private var`.
In case of using private subviews we place them in `Private Properties` section and after new line there are others private vars. The overall logic is to place any public vars on the top that helps easier to understand the interface of a class.

**Comment by ssayfulin69** [comment]
Thank you a lot
